openapi: 3.0.3
info:
  title: Mein Test API
  description: Nur eine Uebung
  contact:
    name: Alican Yildirim
    url: https://github.com/alican-yildirim
    email: aliicann.yildirim@hotmail.com
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
  version: 2.16.5
tags:
  - name: Login
    description: hier befinden sich Methoden zum Login oder Registrieren
paths:
  /login:
    post:
      tags:
        - Login
      operationId: registerUser
      description: Diese Methode legt einen User in der DB Tabelle an.
      requestBody:
        content:
          'application/json':
            schema:
              $ref: '#/components/schemas/LoginDaten'
      responses:
        200:
          description: User existiert und wird somit eingeloggt!
          content:
            application/json:
              schema:
                type: boolean
    get:
      tags:
        - Login
      operationId: loginUser
      description: Diese Methode prüft, ob der user in der DB Tabelle existiert. Falls ja, dann wird TRUE returned, andernfalls FALSE.
      parameters:
        - $ref: '#/components/parameters/Email'
        - $ref: '#/components/parameters/Passwort'
      responses:
        200:
          description: OK - fruits list
          content:
            application/json:
              schema:
#                default: ...
                type: boolean

components:
  parameters:
    Email:
      name: email
      in: query
      description: email angeben
      required: true
      schema:
        type: string
    Passwort:
      name: passwort
      in: query
      description: passwort angeben
      required: true
      schema:
        type: string

  schemas:
    Namen:
      type: object
      properties:
        vorname:
          type: string
        nachname:
          type: string
      required:
        - vorname
        - nachname
    LoginDaten:
      type: object
      properties:
        vorname:
          type: string
        nachname:
          type: string
        email:
          type: string
        passwort:
          type: string
        geschlecht:
          type: integer
        alter:
          type: integer
      required:
        - vorname
        - nachname
        - passwort
        - email
        - geschlecht