package org.acme;

import io.quarkiverse.openapi.generator.annotations.GeneratedMethod;
import io.quarkiverse.openapi.generator.annotations.GeneratedParam;
import io.vertx.core.Future;
import io.vertx.pgclient.PgPool;
import io.vertx.sqlclient.Row;
import io.vertx.sqlclient.RowSet;
import jakarta.annotation.PostConstruct;
import jakarta.inject.Inject;
import jakarta.ws.rs.GET;
import jakarta.ws.rs.Produces;
import jakarta.ws.rs.QueryParam;
import org.openapi.quarkus.openapi_yaml.api.BegruesungenApi;
import org.openapi.quarkus.openapi_yaml.model.Namen;

import java.sql.ResultSet;

public class BegruesungenRessource implements BegruesungenApi {

    private static String res;
    @Inject
    PgPool client;

    public String findAll(PgPool PgClient){

        PgClient.query("SELECT id, title FROM hallo").execute(ar -> {
            if (ar.succeeded()) {
                RowSet<Row> rows = ar.result();
                for (Row row : rows) {
                    res = row.getString(0) + " " + row.getString(1);
                }
            } else {
                res =  "Failure: " + ar.cause().getMessage();
            }
        });

        return res;
    }

    @Override
    public String gruesenGet(String vorname, String nachname) {

        String sql = "CREATE TABLE PEOPLE (ID int generated by default as identity (start with 1 increment by 1) not null," +
                "FNAME varchar(255), LNAME varchar(255), SHOE_SIZE int);";

//        ---------------------------------------------------------   CREATE TABLE
//        client.query(sql).execute(execute -> {
//            if (execute.succeeded()) {
//                System.out.println("Table created !");
//            } else {
//                System.out.println("Table NOT created !");
//            }
//        });

//        ---------------------------------------------------------   INSERT VALUES
//        client.query("INSERT INTO PEOPLE (FNAME, LNAME, SHOE_SIZE) VALUES ('aygül', 'yildirim', 37)").execute(execute -> {
//            if (execute.succeeded()) {
//                System.out.println("Inserted !");
//            } else {
//                System.out.println("NOT Inserted !");
//            }
//        });

//        ---------------------------------------------------------   SELECT SIZE
//        client.query("SELECT * FROM PEOPLE").execute(ar -> {
//
//            if (ar.succeeded()) {
//                System.out.println("SELECT was successful !");
////              System.out.println("Size:  " + ar.result().size());  // SIZE
//            } else {
//                System.out.println("Failure: " + ar.cause().getMessage());
//            }
//        });

//        ---------------------------------------------------------   SELECT VALUES
//        client.preparedQuery("SELECT * FROM PEOPLE").execute(ar -> {
//            if (ar.succeeded()) {
//                RowSet<Row> rows = ar.result();
//                for (Row row : rows) {
//                    System.out.println(row.getInteger(0) + " " + row.getString(1) + " " + row.getString(2) + " " + row.getInteger(3));
//                }
//            } else {
//                System.out.println("Failure: " + ar.cause().getMessage());
//            }
//        });

        return "";
    }

    @Override
    public String gruesenPost(Namen namen) {
        return "Hallo " + namen.getVorname() + " " + namen.getNachname() + "!";
    }
}
