package org.acme;

import io.vertx.pgclient.PgPool;
import jakarta.inject.Inject;
import org.openapi.quarkus.openapi_yaml.api.LoginApi;
import org.openapi.quarkus.openapi_yaml.model.LoginDaten;
import io.vertx.sqlclient.Row;
import io.vertx.sqlclient.RowSet;

public class LoginRessource implements LoginApi {

    @Inject
    PgPool client;

    @Override
    public String loginUser(String email, String passwort) {

        client.query("SELECT * FROM PEOPLE").execute(ar -> {
            if (ar.succeeded()) {
                RowSet<Row> rows = ar.result();
                for (Row row : rows) {
                    System.out.println(row.getInteger(0) + " " + row.getString(1) + " " + row.getString(2) + " " + row.getInteger(3));
                }
            } else {
                System.out.println("Failure: " + ar.cause().getMessage());
            }
        });
        return "true";
    }

    @Override
    public Boolean registerUser(LoginDaten loginDaten) {
        return null;
    }

}




//    String sql = "CREATE TABLE PEOPLE (ID int generated by default as identity (start with 1 increment by 1) not null," +
//            "FNAME varchar(255), LNAME varchar(255), SHOE_SIZE int);";

//        ---------------------------------------------------------   CREATE TABLE
//        client.query(sql).execute(execute -> {
//            if (execute.succeeded()) {
//                System.out.println("Table created !");
//            } else {
//                System.out.println("Table NOT created !");
//            }
//        });

//        ---------------------------------------------------------   INSERT VALUES
//        client.query("INSERT INTO PEOPLE (FNAME, LNAME, SHOE_SIZE) VALUES ('aygül', 'yildirim', 37)").execute(execute -> {
//            if (execute.succeeded()) {
//                System.out.println("Inserted !");
//            } else {
//                System.out.println("NOT Inserted !");
//            }
//        });

//        ---------------------------------------------------------   SELECT SIZE
//        client.query("SELECT * FROM PEOPLE").execute(ar -> {
//
//            if (ar.succeeded()) {
//                System.out.println("SELECT was successful !");
////              System.out.println("Size:  " + ar.result().size());  // SIZE
//            } else {
//                System.out.println("Failure: " + ar.cause().getMessage());
//            }
//        });

//        ---------------------------------------------------------   SELECT VALUES
//        client.query("SELECT * FROM PEOPLE").execute(ar -> {
//            if (ar.succeeded()) {
//                RowSet<Row> rows = ar.result();
//                for (Row row : rows) {
//                    System.out.println(row.getInteger(0) + " " + row.getString(1) + " " + row.getString(2) + " " + row.getInteger(3));
//                }
//            } else {
//                System.out.println("Failure: " + ar.cause().getMessage());
//            }
//        });